version: "15"
services:
  db:
    image: postgres
    container_name: postgres_support
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senhasecreta
